export const defaultCategories = [
  { value: "arts_crafts", label: "Arts & Crafts" },
  { value: "books", label: "Books" },
  { value: "brand", label: "Brand" },
  { value: "beauty_cosmetics", label: "Beauty & Cosmetics" },
  { value: "computer_electronics", label: "Computer & Electronics" },
  { value: "fashion_clothing", label: "Fashion & Clothing" },
  { value: "food", label: "Food" },
  { value: "furniture", label: "Furniture" },
  { value: "groceries", label: "Groceries" },
  { value: "health_fitness", label: "Health & Fitness" },
  { value: "home_kitchen", label: "Home & Kitchen" },
  { value: "industrial_scientific", label: "Industrial & Scientific" },
  { value: "pet_supplies", label: "Pet supplies" },
  { value: "technology", label: "Technology" },
  { value: "toys_games", label: "Toys & Games" },
];
