name: "Deploy Production"
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: "U7y3D7TO5GP5xRKPpL3jKcUy"
          vercel-project-id: "prj_hChZJer1D7KCyrj2FZnjiyXPHpb5"
          vercel-args: "--prod"
